package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.model.Admin;
import com.example.accessingdatamysql.repository.AdminRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/addAdmin") // This means URL's start with /demo (after Application path)
public class AdminController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private AdminRepository adminRepository;


  @PostMapping(path="/addAdmin/test") // Map ONLY POST Requests
  public @ResponseBody String addNewAdmin (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Admin n = new com.example.accessingdatamysql.model.Admin();
    n.setName(name);
    n.setEmail(email);
    adminRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Admin> getAllAdmins() {
    // This returns a JSON or XML with the users
    return adminRepository.findAll();
  }
}
