package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.model.Student;
import com.example.accessingdatamysql.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/student") // This means URL's start with /demo (after Application path)
public class StudentController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private StudentRepository studentRepository;


  @PostMapping(path="/student/addStudent") // Map ONLY POST Requests
  public @ResponseBody String addNewStudent (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Student n = new com.example.accessingdatamysql.model.Student();
    n.setName(name);
    n.setEmail(email);
    studentRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Student> getAllStudents() {
    // This returns a JSON or XML with the users
    return studentRepository.findAll();
  }
}
